# Generated by Django 4.2.4 on 2023-12-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_hospital', models.CharField(max_length=200)),
                ('hospital_number', models.CharField(max_length=200)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_app.city')),
            ],
        ),
    ]
